on:
  pull_request:
    branches: main
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

jobs:
  pr_check:
    runs-on: ubuntu-latest
    env:
      TORCH_INSTALL: 1
    uses: r4ds/r4dsactions/.github/workflows/render_check.yml@main
